server :
  port: 8888
spring :
  liquibase :
    change-log: classpath*:migrations/master-changelog.yml
mybatis:
  type-handlers-package: ru.relex.library.db.handlers
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
